[build-system]
requires = ["maturin>=0.12,<0.13", "setuptools", "wheel", "setuptools-rust"]
build-backend = "maturin"

[project]
name = "fastsim"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]