[tool.poetry]
name = "fastsim"
version = "1.2.6"
description = "The Future Automotive Systems Technology Simulator (FASTSim) provides a simple way to compare powertrains and estimate the impact of technology improvements on light-, medium-, and heavy-duty vehicle efficiency, performance, cost, and battery life."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = " >=3.7,<3.11"
numba = "^0.55.1"
seaborn = "^0.11.2"
matplotlib = "^3.5.1"
pandas = "^1"

[tool.poetry.dev-dependencies]
openpyxl = {version = "^3.0.9", platform = "windows"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
