//! Serde `serialize_with` helpers for SI quantities in non-base units.
//!
//! Generated by [`crate::impl_si_serialize_as!`], which creates five variants
//! per quantity/unit pair:
//!
//! | Function              | Field type                   |
//! |-----------------------|------------------------------|
//! | `{prefix}`            | `Qty`                        |
//! | `tracked_{prefix}`    | `TrackedState<Qty>`          |
//! | `opt_{prefix}`        | `Option<Qty>`                |
//! | `vec_{prefix}`        | `Vec<Qty>`                   |
//! | `vec_tracked_{prefix}`| `Vec<TrackedState<Qty>>`     |
//!
//! # Activating non-base serialization for a quantity
//!
//! Two coordinated changes in `fastsim-proc-macros/src/serde_api/serde_utils.rs`
//! are needed — both live in the same arm of `quantity_config`:
//!
//! 1. Move the target unit to first position (first = canonical serialization unit).
//! 2. Set `serialize_with` to the matching helper path.
//!
//! ```text
//! // Current (serializes in watts):
//! "Power" => Some((
//!     extract_units!(uom::si::power::watt, uom::si::power::kilowatt, ...),
//!     None,
//! )),
//!
//! // To serialize in kilowatts:
//! "Power" => Some((
//!     extract_units!(uom::si::power::kilowatt, uom::si::power::watt, ...),
//!     Some("fastsim_core::utils::serde_helpers::power_as_kilowatts"),
//! )),
//! ```
//!
//! Then uncomment the matching `impl_si_serialize_as!` call below.

#[allow(unused_imports)]
use crate::si;

// ── Power ────────────────────────────────────────────────────────────────────
crate::impl_si_serialize_as!(power_as_kilowatts, si::Power, uom::si::power::kilowatt);
