//! Serde `serialize_with` helpers for SI quantities in non-base units.
//!
//! Generated by [`crate::impl_si_serialize_as!`], which creates wrapper-specific variants
//! per quantity/unit pair:
//!
//! | Function              | Field type                   |
//! |-----------------------|------------------------------|
//! | `{prefix}`            | `Qty`                        |
//! | `tracked_{prefix}`    | `TrackedState<Qty>`          |
//! | `opt_{prefix}`        | `Option<Qty>`                |
//! | `vec_{prefix}`        | `Vec<Qty>`                   |
//! | `vec_tracked_{prefix}`| `Vec<TrackedState<Qty>>`     |
//! | `tracked_opt_{prefix}`| `TrackedState<Option<Qty>>`  |
//! | `opt_tracked_{prefix}`| `Option<TrackedState<Qty>>`  |
//! | `vec_tracked_opt_{prefix}`| `Vec<TrackedState<Option<Qty>>>` |
//!
//! # Activating non-base serialization for a quantity
//!
//! Two coordinated changes in `fastsim-proc-macros/src/serde_api/serde_utils.rs`
//! are needed — both live in the same arm of `quantity_config`:
//!
//! 1. Move the target unit to first position (first = canonical serialization unit).
//! 2. Set `serialize_with` to the matching helper path.
//!
//! ```text
//! // Current (serializes in watts):
//! "Power" => Some((
//!     extract_units!(uom::si::power::watt, uom::si::power::kilowatt, ...),
//!     None,
//! )),
//!
//! // To serialize in kilowatts:
//! "Power" => Some((
//!     extract_units!(uom::si::power::kilowatt, uom::si::power::watt, ...),
//!     Some("fastsim_core::utils::serde_helpers::power_as_kilowatts"),
//! )),
//! ```
//!
//! Then uncomment the matching `impl_si_serialize_as!` call below.

#[allow(unused_imports)]
use crate::si;

crate::impl_si_serialize_as!(energy_as_kilojoules, si::Energy, uom::si::energy::kilojoule);
crate::impl_si_serialize_as!(
    energy_as_kilowatt_hours,
    si::Energy,
    crate::si::kilowatt_hour
);
crate::impl_si_serialize_as!(power_as_kilowatts, si::Power, uom::si::power::kilowatt);
crate::impl_si_serialize_as!(
    pressure_as_kilopascals,
    si::Pressure,
    uom::si::pressure::kilopascal
);
crate::impl_si_serialize_as!(ratio_as_percent, si::Ratio, uom::si::ratio::percent);
crate::impl_si_serialize_as!(
    specific_energy_as_kilowatt_hours_per_kilogram,
    si::SpecificEnergy,
    crate::si::kilowatt_hour_per_kilogram
);
crate::impl_si_serialize_as!(
    specific_power_as_kilowatts_per_kilogram,
    si::SpecificPower,
    crate::si::kilowatt_per_kilogram
);
crate::impl_si_serialize_as!(
    temperature_as_degrees_celsius,
    si::Temperature,
    uom::si::thermodynamic_temperature::degree_celsius
);
crate::impl_si_serialize_as!(
    temperature_interval_as_degrees_celsius,
    si::TemperatureInterval,
    uom::si::temperature_interval::degree_celsius
);
