//! Serde `serialize_with` helpers for SI quantities in non-base units.
//!
//! Generated by [`crate::impl_si_serialize_as!`], which creates four variants
//! per quantity/unit pair:
//!
//! | Function              | Field type                   |
//! |-----------------------|------------------------------|
//! | `{prefix}`            | `Qty`                        |
//! | `tracked_{prefix}`    | `TrackedState<Qty>`          |
//! | `opt_{prefix}`        | `Option<Qty>`                |
//! | `vec_{prefix}`        | `Vec<Qty>`                   |
//!
//! # Activating non-base serialization for a quantity
//!
//! In `fastsim-proc-macros/src/serde_api/serde_utils.rs`, each quantity arm
//! returns `(unit_impls, serialize_with)` together.  To serialize Power in
//! kilowatts, change the `"Power"` arm from:
//!
//! ```text
//! "Power" => (extract_units!(uom::si::power::watt), None),
//! ```
//! to:
//! ```text
//! "Power" => (
//!     extract_units!(uom::si::power::kilowatt),
//!     Some("fastsim_core::utils::serde_helpers::power_as_kilowatts"),
//! ),
//! ```

use crate::si;

// ── Power ────────────────────────────────────────────────────────────────────
// crate::impl_si_serialize_as!(power_as_kilowatts, si::Power, uom::si::power::kilowatt);
