[package]
name = "fastsimrust"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fastsimrust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
ndarray = { version = "0.15.4", features=["serde"]}
csv = "1.1"
proc_macros = { path = "proc_macros" }
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
bincode = "1.3.3"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/html/docs-header.html" ]

[profile.release]
# https://deterministic.space/high-performance-rust.html
opt-level = 3               # Use better optimizations.
lto = "fat"  # aggressively optimize inter-crate linking
codegen-units = 1  # optimize connection between modules
