name: build_windows

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # '[0-9]+.[0-9]+.[0-9]+' to match e.g. 2.0.8

jobs:
  publish-windows:
    name: Publish binary windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/regostry
          ~/.cargo/git
          ~/.rustup
          target
        key: windows-latest-stable

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Build
      run: |
        cd rust
        rustup target add x86_64-pc-windows-gnu
        cargo build --release --target x86_64-pc-windows-gnu

    - name: Package artifacts
      run: |
        $RELEASE_VERSION=${env:GITHUB_REF_NAME}
        $ASSET_NAME="rust/fastsim-cli-${RELEASE_VERSION}-x86_64-pc-windows-gnu.zip"
        Compress-Archive rust/target/x86_64-pc-windows-gnu/release/fastsim-cli.exe $ASSET_NAME
        echo "ASSET_NAME=${ASSET_NAME}" >> $env:GITHUB_ENV

        $CHECKSUM_NAME="${ASSET_NAME}.sha256"
        CertUtil -hashfile $ASSET_NAME sha256 > $CHECKSUM_NAME
        echo "CHECKSUM_NAME=${CHECKSUM_NAME}" >> $env:GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.ASSET_NAME }}
          ${{ env.CHECKSUM_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}