# name: rust-tests

# on:
#   push:
#       branches: [fastsim-2, fastsim-3]
#   pull_request:
#   workflow_dispatch:
#   workflow_call:

# jobs:
#   test:
#     # might not be needed
#     # if: github.repository == 'nrel/fastsim'

#     runs-on: ubuntu-latest

#     strategy:
#       fail-fast: true
#       # matrix:
#       #   python-version: ['3.8', '3.9', '3.10']

#     # env:
#     #   PYTHON: ${{ matrix.python-version }}
#     steps:
#     - uses: actions/checkout@v3

#     # - name: set up python ${{ matrix.python-version }}
#     #   uses: actions/setup-python@v4
#     #   with:
#     #     python-version: ${{ matrix.python-version }}

#     # if: contains(github.event.pull_request.changed_files, 'rust/')
#     - name: install rust
#       uses: actions-rs/toolchain@v1
#       with:
#         profile: minimal
#         toolchain: stable
#         override: true

#     - name: Rust unit tests
#       run: |
#         cd rust/ && cargo test