name: tests 

on:
  push:
      branches: 
        - fastsim-2 
        - fastsim-3
  pull_request:

jobs:
  test:
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          python-version: ['3.8', '3.9', '3.10']

      env:
        CIBW_BUILD: "cp3${{ matrix.python-version }}-*"
        CIBW_SKIP: "*-win32 *-musllinux* *i686 *ppc64le *s390x *aarch64"
        CIBW_TEST_REQUIRES: "pytest"
        CIBW_TEST_COMMAND: "pytest {project}/fastsim/tests -s"
        CIBW_ARCHS_MACOS: 'universal2'
        # see https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2
        CIBW_TEST_SKIP: '*_universal2:arm64'
        CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
        CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2014"
        CIBW_MANYLINUX_I686_IMAGE: "manylinux2014"
        CIBW_BEFORE_BUILD: >
          pip install -U setuptools-rust &&
          rustup default stabel &&
          rustup show
        CIBW_BEFORE_BUILD_LINUX: >
          pip install -U setuptools-rust &&
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable --profile=minimal -y &&
          rustup show

      steps:
      - uses: actions/checkout@v2

      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Rust unit tests
        run: |
          cd rust/
          cargo test

      - name: Python unit tests 
        run: |
          pip install setuptools_rust 
          pip install . 
          pytest -v fastsim/tests/
